### PR TITLE
Fix gcc build errors

### PR DESCRIPTION
**Pull request by z33ky**

### CODE REVIEW

**Comment by samisalreadytaken** [comment]
I did not get a notification or an email about this. Newer commits seem to have created conflicts, I'll add these myself, thanks.

Do you know why this does not work in gcc? It's just straight forward inheritance.

**Comment by z33ky** [comment]
It's a standard compliance thing. Normally the lookup for identifiers is allowed to ignore templates. Could be an optimization thing so the compiler can compile stuff ahead of template-instantation if it does not depend on templates, I dunno. Using `this->` (alternatively `BaseClass::` or similar also works, although the Source SDK uses `this->` more often) states that the lookup may be template-parameter dependent.

**Comment by samisalreadytaken** [comment]
Wouldn't `_vpanel` and `m_hScriptInstance` inside `CScriptVGUIObject::Destroy` also require `this->` when `GetVPanel()` does?

Similiarly don't `_base` and `_vpanel` inside `CScript_Panel_Helper::Create` (from the macro `DECLARE_SCRIPTVGUI_HELPER`) also require it?

**Comment by z33ky** [comment]
For `CScriptVGUIObject::Destroy()` these variables are not dependant on the template value, i.e. they will *always* exist.
If a specialization of `CScriptVGUIObject` existed that does not inherit `IScriptVGUIObject` this also won't get the (inline-)defined `CScriptVGUIObject::Destroy()` so `_vpanel` and `m_hScriptInstance` will always refer to `IScriptVGUIObject::{_vpanel,m_hScriptInstance}`.

For `CScript_Panel_Helper::Create()` the current usages inherit an `CScriptVGUIObject` with a concrete `T`, i.e. the template is already resolved.
If you were to add a class such as a `template<typename T> class CScript_Generic_Helper : public IScript_Panel<T>` then `DECLARE_SCRIPTVGUI_HELPER()` wouldn't work and would need the `this->`. It doesn't hurt to change the macro to use `this->` in case.

I didn't go through each error individually, I simply did a regex replacement. I see now that it was a bit overly eager - some cases from this change do not require the `this->`.
Let me send you [this compile log](https://gist.github.com/z33ky/8baf347a09a69acdb58e88a6dbd826d2) of the current version of your branch.

**Comment by samisalreadytaken** [comment]
Thanks again.

**Pull request closed without merging**
